CREATE TABLE todos (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    todo TEXT NOT NULL,
    who TEXT NOT NULL,
    created TEXT NOT NULL,
    due TEXT NOT NULL,
    status TEXT,
    status_date TEXT,
    reviewed TEXT,
    issue INTEGER
        REFERENCES issues(id) ON DELETE SET NULL
);